### ISSUE TITLE
TK #05 - Proyectar la Presentación del Formulario de Contacto

### ISSUE THREAD

**Issue by facumd** [NicoRojo62/FullStackDevIspc#15]
> Fomato Propuesto por Viviana

![Image](https://user-images.githubusercontent.com/95236196/195606944-cfd03d0c-2538-449c-a21a-f429d72d8d59.png)

**Comment by facumd** [comment]
Me parece un excelente punto de partida!

**Comment by vmgith** [comment]
Dentro de dicho formulario también debemos ofrecer al usuario  'Información de Contacto' , donde se informa todas las vías posibles para contartarse con la empresa tanto números telefónicos como redes sociales .

[InformacionContacto.docx](https://github.com/NicoRojo62/FullStackDevIspc/files/9712295/InformacionContacto.docx)

**Comment by facumd** [comment]
Muy bueno el formato y los colores Vivi 🙌

**Comment by Marianella93** [comment]
Muy bueno Vivi, no se si sea importante pero he visto en algunas páginas de inmobiliarias que ponen una sección de -como nos conociste- (Por un amigo, por redes sociales, etc..)
