### ISSUE TITLE
US #05  - Como Cliente: Quiero Adaptabilidad De Página Web

### ISSUE THREAD

**Issue by carosara** [NicoRojo62/FullStackDevIspc#18]
Como cliente quiero que el producto se adapte a distintos dispositivos para dar mas accesibilidad a los usuarios

**Comment by PsicoDevil** [comment]
Se Probaron las paginas y todas responden a un modelo Responsive y se Adaptan a Diferentes Dispositivos

**Comment by facumd** [comment]
No creo que el responsive esté funcionando correctamente aun, debe pasar a revisión y corregirse de ser el caso

**Comment by facumd** [comment]
> No creo que el responsive esté funcionando correctamente aun, debe pasar a revisión y corregirse de ser el caso

Resuelto en parte, hasta donde se pudo con lo que habia...
