### ISSUE TITLE
Incidente #00 - Sprint 0

### ISSUE THREAD

**Issue by facumd** [NicoRojo62/FullStackDevIspc#19]
Escribo esto a modo de Feedback, con respecto a algunos puntos que veo, deberíamos mejorar en el siguiente sprint. Esta es solo una crítica constructiva, por mi parte, para el bienestar y mejora del grupo sobre la que creo, debemos tomar cartas en el asunto. (No espero que se sientan señalados ni ofendidos al leer esto, ya que somos un grupo y estamos el uno para el otro, ante las situaciones que puedan surgir en la vida, tanto al nivel del grupo como en lo personal de cada uno)

- Promover una mayor participación en el repositorio:
    - Solo cuando sea posible y en sus tiempos libres (aunque sea una vez cada 3 días) intentemos entrar el repositorio y ver los nuevos cambios para estar al tanto de ellos, aun así como lo venimos haciendo, comentaremos nuestras adiciones al mismo en el grupo de WhatsApp. 
    
- Aumentar la participación y el debate en los issues:
    - En vista de que no hubo comentarios que retroalimentaran cada issue, solicito que se trabaje en esto y haya un intercambio mínimo cuando sea posible y surjan ideas para saber si todos estamos de acuerdo en el tema y poder seguir adelante.
    
- Falta de aporte a los requerimientos a definir que estaban consignados:
    - Al no haber comentado los issues (señalados abajo) no hubo un despliegue con respecto a como encararemos el sitio web, podríamos haber planteado la paleta de colores, el logotipo, el nombre del sitio web, la estructura del index, la parte de servicios, producto, la home page, el nav, el footer, el perfil del usuario, etc. **Lo que nos deja más tareas para el sprint 1**, en tiempos donde los parciales y las entregas complicarán más el asunto. Solicito que intentemos trabajar más en esto, creando más issues que salgan de las ideas de cada uno y no haya solo aporte de 2 o 3 usuarios en lo que respecta a este menú.
    
- [ ] #17 
- [ ] #3 
- [ ] #1 

Por lo que a mi parecer algunos de estos issues, deberán ser reabiertos para sumar ideas.

- Entrega y subida de archivos a último momento:
    - Entiendo que la situación personal (trabajo-familia) de cada uno puede presentar complicaciones y solo solicito que ante entregas aproximándose podamos realizar las tareas con más tiempo de anticipación, y en caso de necesitar ayuda, no temer preguntar o avisar (de nuevo solicito que sea con **tiempo de anticipación**). Para así poder generar feedback por parte de las otras personas que conforman el grupo, corregir la documentación, e implementar cosas en las que estemos de acuerdo todos o la gran mayoría.

- La explicación del proyecto:
    - A mi parecer, para crear una página de Adm. de Bienes Raíces, debemos entender todo este mundo que encierra. Ventas, alquileres, Tipos de vivienda, tipos de clientes, tipos de usuario, ubicaciones, precios, bienes, etcétera.  Aunque sea un paneo general y específico por parte del especializado en el tema grupo, creo nos vendría bien para poder definir luego con mayor acierto las clases, objetos, módulos a emplear en el desarrollo del sitio web, entre otras cuestiones.

Solicito que podamos hacer cada uno una autorreflexión y promover y opinar esta clase de pensamientos. A su vez, son libres de comentar sobre este issue, sus opiniones al respecto y pensamientos sobre este tema u otras falencias que surgieron en este tramo, el cual fue liviano y sencillo, pero debemos prepararnos para el cierre del semestre a esta altura del año.

**Comment by NicoRojo62** [comment]
excelente propuesta facu. Hay que armar un meet para que Fran nos explique a todos los puntos mas importantes del proyecto.
