### ISSUE TITLE
TK #08 - Realizar un "Prototipo" de las Pantallas

### ISSUE THREAD

**Issue by facumd** [NicoRojo62/FullStackDevIspc#22]
- [x] Definir las "Páginas/Apartados" ej: Home Page, Contacto, Productos, Acerca de... Etc.
- [x] Esquematizar su estructura.
- [x] Programar sus Índices (HTML).

**Comment by facumd** [comment]
![Image](https://user-images.githubusercontent.com/95236196/195604190-77efe4d4-822f-43c8-a120-c4eecdf1b7cc.png)

![Image](https://user-images.githubusercontent.com/95236196/195604240-b271e840-4bef-4a5a-a053-47a64aaefe35.png)

![Image](https://user-images.githubusercontent.com/95236196/195604269-f18d00de-fee0-40a7-bc21-67e02e66c4f3.png)

> Autor: Nicolás Rojo

## Mensajes del Grupo:

_"... Quedarian las funciones del cliente (inquilino) 
Y agregar en funciones de administrador, cargar cobros..."_

_"...Esta bueno, el front end dice con
 1-estructura html, estilos css 
2-navegabilidad, link funcionales. Responsive
3-boostrap
Estaba pensando q en carga de propiedades deben ir imagenes de los inmuebles no?..."_

_"...Ahi debe estar el boton para subir la foto
Si podemos, alguno que acepte link de youtube
Las fotos van en el menu de propiedades
Que es una pagina que me esta faltando, veo..."_

**Comment by facumd** [comment]
- [x] Definir las "Páginas/Apartados" ej: Home Page, Contacto, Productos, Acerca de... Etc.
- [x] Esquematizar su estructura.
    - (Hecho en Mapa de Sitio)
- [-] Programar sus Índices (HTML).
    - (Crear Un Issue correspondiente a esto en su momento)

**Comment by vmgith** [comment]
Buenisimo FAcu, dentro de las funciones del Administrador incluiria el mantenieniento de la tabla de Clientes, altas y actualizacion de datos.

**Comment by vmgith** [comment]
En buscador creo que zona de preferencia y zona serian redundantes.
