### ISSUE TITLE
TK #09 - Dividir el grupo en grupos más pequeños con concordancia de horarios

### ISSUE THREAD

**Issue by facumd** [NicoRojo62/FullStackDevIspc#23]
Al charlar con otra gente en los grupos de What's app, me comentaron que lo que hacía era subdividir el grupo en pequeños grupos de trabajo a modo de equipos de desarrollos, los cuales se encargan de tares especificas tanto del Frontend como del Backend.

Una sugerencia de los demás compañeros fue dividir sus grupos en 3 grupos (3-3-4), otros los dividieron en 5 grupos (2-2-2-2-2).

Sugiero hacer lo mismo para así poder repartir las tareas con gente que tenga en común sus horarios libres:

Podemos hacer un Google Form donde informemos nuestros días libres, aclararlos como comentario aquí abajo o informarlos por wpp.

    Queda a decisión del grupo

**Comment by facumd** [comment]
Por mi parte mis días libres son Viernes (Todo el dia) y Domingos (A partir de las 17:00 o 18:00 hs) 
Los demás días, trabajo y los sábados (Estoy disponible en mis descansos solo momentos breves para consultas y charlar algunos temas vía What's app)

**Comment by facumd** [comment]
- [ ] Acordar Concordancia de Horarios
- [x] Dividir Tareas en Sub-Grupos

**Comment by Marianella93** [comment]
Hola a todos, mis días libres, de lunes a sábado por la mañana hasta las 15:30-16:00, y los domingos todo el día, y comentarios por WhatsApp todo el día
