### ISSUE TITLE
US #07 - Como Cliente: Quiero Una Página de Usuario 

### ISSUE THREAD

**Issue by facumd** [NicoRojo62/FullStackDevIspc#25]
- Inquilino: debe poder acceder al link de pago, comunicar problemas, preavisos, cargar una pre-nota/comprobante.

**Comment by PsicoDevil** [comment]
En mi branch deje HTML, CSS + BOOSTRAP De la Pagina Final de Usuario (usuario.html) 

Trabajo realizado con @Marianella93 @Franbelt1


Saludos
