### ISSUE TITLE
TK #11 - Definir el Tipo de Ceremonia (Reunión Desarrollada)

### ISSUE THREAD

**Issue by facumd** [NicoRojo62/FullStackDevIspc#28]
A partir de la devolución del Tutor, queda esta tarea pendiente.

![image](https://user-images.githubusercontent.com/95236196/195610975-2fdbfc46-3091-4d49-98cb-49ec561afb76.png)

Profe Mainero Alejandro

### Referencias de Valoración:

* LOGRADO (completo)

* EN PROCESO (Falta trabajo)

* NO LOGRADO (Presentado pero erróneo)

* NO EVIDENCIA (No hay registro)

-----------------

Por otro lado, también se debe:

- [x] Subir Reunión Resgristo de Meeting Fecha: 11/10/22
    - Debe hacerse con su respectiva aclaración de: Tipo de Ceremonia

**Comment by PsicoDevil** [comment]
Facu ya cargue el Sprint Planning realizado el Martes en Wiki y Seccion Meetings

Saludos

[https://github.com/NicoRojo62/FullStackDevIspc/wiki/Meet-:-Sprint-Planning--11-10-2022](url)
