### ISSUE TITLE
Coordinar un meet

### ISSUE THREAD

**Issue by NicoRojo62** [NicoRojo62/FullStackDevIspc#31]
el objetivo es que Fran pueda explicar a los compañero que no tienen claro el mundo inmobiliario, los detalles del negocio y que cosas son mas o menos importantes desde el punto de vista de modelo de negocio. Si algún compañero alquila, tambien podemos revisar el punto de vista del inquilino, para comprender mejor los problemas.

**Comment by vmgith** [comment]
Estoy de acuerdo, tengo disponibilidad hoy

**Comment by Franbelt1** [comment]
Si chicos no hay problema podemos organizar una meet para esta noche y yo les puedo dar los parametros generales del rubro para que tengamos una idea conjunta de lo que se busca plasmar en este modelo web
