### ISSUE TITLE
TK #15 - Construcción de Clases en "Python"

### ISSUE THREAD

**Issue by facumd** [NicoRojo62/FullStackDevIspc#51]
Debemos crear las clases usando Python a partir de lo aprendido tanto en cisco como de los videos explicativos

**Comment by vmgith** [comment]
Hola, ya estoy viendo este tema

**Comment by facumd** [comment]
Buenisimo vivi! 🙌🏽

**Comment by vmgith** [comment]
Diagrama de Clases  version 1.0 
![DiagramaDeClases](https://user-images.githubusercontent.com/105835509/197378350-182207c0-1cee-4823-a72c-b3c6183dd37b.png)

**Comment by facumd** [comment]
Hola Vivi, como estas? 

- Primero que nada te confudiste de issue, este era para crear las clases en lenguaje Python, de la siguiente manera, te dejo un ejemplo práctico que se encuentra en la guía de POO: 

```py
class Moto: 
    Marca = ""
    Modelo = ""
    Patente= ""
    Kilometraje= 0

    def __init__(self, marca, modelo, patente, kilometraje ):
        self.Marca = marca
        self.Modelo= modelo
        self.Patente= patente
        self.Kilometraje= kilometraje

    def get_Marca(self):
        return self.Marca

    def set_Marca(self, marca):
        self.Marca = marca 
    
    def get_Modelo(self):
        return self.Modelo

    def set_Modelo(self, modelo):
        self.Modelo = modelo

    def get_Patente(self):
        return self.Patente

    def set_Patente(self, patente):
        self.Patente = patente

    def get_Kilometraje(self):
        return self.Kilometraje

    def set_Kilometraje(self, kilometraje):
        self.Kilometraje = kilometraje

    def __str__(self):
    return ('La marca de la moto es:' + self.Marca + ' modelo: ' + self.Modelo + 'su patente es: '+ self.Patente + 'y el kilometraje es: 'str(self.Kilometraje))

marca= input('Ingrese la marca de la moto.')
modelo= input('Ingrese el modelo de la moto.')
patente= input('Ingrese la patente de la moto.')
kilometraje= input('Ingrese el kilometraje de la moto.')

miMoto= Moto(marca,modelo,patente,kilometraje)

miMoto.__str__()
```

Se entiende tu confusión ya que el issue está explicado con las palabras que había en el archivo: 

> Presentación Proyecto Integrador 
..."En segundo lugar, la construcción de las clases utilizando el lenguaje de programación en Python. Hay videos explicativos en el apartado de Backend."...

- Por otro lado, este diagrama ya fue realizado y subido a su issue correspondiente y a la wiki el dia 20/10/22:

    - #45 

- En cuanto a tu diagrama lo veo bastante bien, solo que en atributos como cbu, dni y otros no deberían ser `string`, si no `number`: ya sea `int` o `float`.

Por otro lado cuando hay herencia, no se repiten en la otra clase los métodos ya que con la forma de la flecha entendemos que ese atributo heredará dichos métodos.

Y por último, creo que estas planteando atributos que el sitio web no está pidiendo o usando, ya que si nevegas por los indices (Por ej. Galería), no vas a encontrar opciones en las propiedades como pscina, cantidad de baños, etc.

Esto supone un problema ya que si planteamos atributos que el programa no usará o tenemos repetición, esto significará más memoria en el disco, y mas inversión de parte del cliente (En este proyecto lo ultimo no tiene sentido pero las buenas prácticas hay que seguirlas...)

- Propongo que hagamos una reunión entre vos @vmgith, yo @facumd y @soapmanu, quien realizó algunos diagramas de procesos, pero no estoy viendo que usemos las mismas entidades y atributos. En la reunión debemos acordar de una vez por todas que entidades y atributos vamos a plantear para el modelo definitivo de negocios con la ventaja de que ya planteamos varias podemos ver cuales nos quedamos justificándonos en su uso, según el alcance que hasta ahora intentamos darle. Espero te tomes el tiempo de leer esto y revisar el repositorio en los puntos que te señalé. Saludos

> Diagrama de Clases version 1.0 ![DiagramaDeClases](https://user-images.githubusercontent.com/105835509/197378350-182207c0-1cee-4823-a72c-b3c6183dd37b.png)

**Comment by facumd** [comment]
Agregué las clases, falta trabajar en los diagramas y discutir temas que no se han tratado hasta el momento, pero tenemos la base del proyecto

> Hola Vivi, como estas?
> 
> * Primero que nada te confudiste de issue, este era para crear las clases en lenguaje Python, de la siguiente manera, te dejo un ejemplo práctico que se encuentra en la guía de POO:
> 
> ```python
> class Moto: 
>     Marca = ""
>     Modelo = ""
>     Patente= ""
>     Kilometraje= 0
> 
>     def __init__(self, marca, modelo, patente, kilometraje ):
>         self.Marca = marca
>         self.Modelo= modelo
>         self.Patente= patente
>         self.Kilometraje= kilometraje
> 
>     def get_Marca(self):
>         return self.Marca
> 
>     def set_Marca(self, marca):
>         self.Marca = marca 
>     
>     def get_Modelo(self):
>         return self.Modelo
> 
>     def set_Modelo(self, modelo):
>         self.Modelo = modelo
> 
>     def get_Patente(self):
>         return self.Patente
> 
>     def set_Patente(self, patente):
>         self.Patente = patente
> 
>     def get_Kilometraje(self):
>         return self.Kilometraje
> 
>     def set_Kilometraje(self, kilometraje):
>         self.Kilometraje = kilometraje
> 
>     def __str__(self):
>     return ('La marca de la moto es:' + self.Marca + ' modelo: ' + self.Modelo + 'su patente es: '+ self.Patente + 'y el kilometraje es: 'str(self.Kilometraje))
> 
> marca= input('Ingrese la marca de la moto.')
> modelo= input('Ingrese el modelo de la moto.')
> patente= input('Ingrese la patente de la moto.')
> kilometraje= input('Ingrese el kilometraje de la moto.')
> 
> miMoto= Moto(marca,modelo,patente,kilometraje)
> 
> miMoto.__str__()
> ```
> 
> Se entiende tu confusión ya que el issue está explicado con las palabras que había en el archivo:
> 
> > Presentación Proyecto Integrador
> > ..."En segundo lugar, la construcción de las clases utilizando el lenguaje de programación en Python. Hay videos explicativos en el apartado de Backend."...
> 
> * Por otro lado, este diagrama ya fue realizado y subido a su issue correspondiente y a la wiki el dia 20/10/22:
>   
>   * [TK #13 - Diseñar Modelo/Diagrama de Clases #45](https://github.com/NicoRojo62/FullStackDevIspc/issues/45)
> * En cuanto a tu diagrama lo veo bastante bien, solo que en atributos como cbu, dni y otros no deberían ser `string`, si no `number`: ya sea `int` o `float`.
> 
> Por otro lado cuando hay herencia, no se repiten en la otra clase los métodos ya que con la forma de la flecha entendemos que ese atributo heredará dichos métodos.
> 
> Y por último, creo que estas planteando atributos que el sitio web no está pidiendo o usando, ya que si nevegas por los indices (Por ej. Galería), no vas a encontrar opciones en las propiedades como pscina, cantidad de baños, etc.
> 
> Esto supone un problema ya que si planteamos atributos que el programa no usará o tenemos repetición, esto significará más memoria en el disco, y mas inversión de parte del cliente (En este proyecto lo ultimo no tiene sentido pero las buenas prácticas hay que seguirlas...)
> 
> * Propongo que hagamos una reunión entre vos @vmgith, yo @facumd y @soapmanu, quien realizó algunos diagramas de procesos, pero no estoy viendo que usemos las mismas entidades y atributos. En la reunión debemos acordar de una vez por todas que entidades y atributos vamos a plantear para el modelo definitivo de negocios con la ventaja de que ya planteamos varias podemos ver cuales nos quedamos justificándonos en su uso, según el alcance que hasta ahora intentamos darle. Espero te tomes el tiempo de leer esto y revisar el repositorio en los puntos que te señalé. Saludos
> 
> > Diagrama de Clases version 1.0 ![DiagramaDeClases](https://user-images.githubusercontent.com/105835509/197378350-182207c0-1cee-4823-a72c-b3c6183dd37b.png)
