### ISSUE TITLE
Devolución Sprint 1

### ISSUE THREAD

**Issue by facumd** [NicoRojo62/FullStackDevIspc#57]
Devolución hecha y escrita por el Profesor Mainero, Alejandro Luis - Miércoles, 12 octubre 2022, 5:36

Registro de avances al 22/10

Estimados,

Luego de analizar su proyecto, les presento los puntos evaluados y la correspondiente devolución:

- Logra conectarse al repositorio GitHub (colaboradores): LOGRADO

- Logra agregar Issues como Historia de Usuarios: LOGRADO

- Logra agregar Milestone por Sprints: LOGRADO

- Logra realizar Commit: LOGRADO

- Logra crear Wiki con registro de ceremonias (daily, review, retrospective) y novedades del equipo: LOGRADO

  Falta de definir el tipo de ceremonia (reunion desarrollada).

- Respeta Nomenclatura de las issues sugeridas: LOGRADO

- Asigna y distribuye issues a cada miembro del equipo:, distribuyan y agreguen las issues diferentes miembros del github. LOGRADO

- Logra documentar el proyecto mediante en IEEE 830 para el cliente: LOGRADO

- Utiliza kanban (Product Backlog, ToDo, In process, Finished): LOGRADO

- Logra Esquematizar sitio  (Mapa de sitio): LOGRADO

Excelente trabajo equipo!! Continuen así!!

Saludos cordiales

Profe Mainero Alejandro

Referencias de Valoración:

LOGRADO (completo)

EN PROCESO (Falta trabajo)

NO LOGRADO (Presentado pero erróneo)

NO EVIDENCIA (No hay registro)

**Comment by PsicoDevil** [comment]
Genial!
